name: release

on:
  push:
    branches:
      - main
      - beta
    tags-ignore:
      - "**"

jobs:
  release:
    if: "! contains(github.event.head_commit.message, '[skip ci]') && ! contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: asdf-vm/actions/install@v2

      - run: |
          deno task build
          asdf global nodejs `node -v | sed 's/v//'`

      - uses: cycjimmy/semantic-release-action@v3
        with:
          working_directory: npm
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

