name: release

on:
  push:
    branches:
      - main
      - beta
    tags-ignore:
      - "**"

jobs:
  release:
    if: "! contains(github.event.head_commit.message, '[skip ci]') && ! contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      
      - run: |
          deno task build

      - uses: cycjimmy/semantic-release-action@v3
        with:
          working_directory: npm
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

