name: release

on:
  push:
    branches:
      - main
      - beta
    tags-ignore:
      - "**"

jobs:
  release:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: asdf-vm/actions/install@v3

      - run: deno task build

      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - uses: cycjimmy/semantic-release-action@v4
        with:
          working_directory: npm
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
