name: test

on:
  pull_request:
    paths:
      - "*.ts"
  push:
    branches:
      - "develop"
    paths:
      - "*.ts"
  workflow_dispatch:

jobs:
  test:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: asdf-vm/actions/install@v3

      - run: deno task build
