name: test

on:
  pull_request:
    paths:
      - "**.ts"
  push:
    branches:
      - "develop"
    paths:
      - "**.ts"
  workflow_dispatch:

jobs:
  test:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: asdf-vm/actions/install@v4

      - run: deno lint src/

      - run: deno fmt --check src/

      - run: deno task test

      - run: deno task build
